name: teads-curve-demo+grafana+mock
description:
tags:
initialize:
  plugins:
    mock-observations:
      path: builtin
      method: MockObservations
      config:
        timestamp-from: 2025-01-01T00:00
        timestamp-to: 2025-01-30T00:00
        duration: 3600
        components:
          - cloud/instance-type: A1
          #- cloud/instance-type: B1
        generators:
          common:
            region: italynorth
            common-key: common-val
          randint:
            cpu/utilization:
              min: 1
              max: 99
            memory/utilization:
              min: 1
              max: 99
    grafana-exporter:
      method: GrafanaExport
      path: https://github.com/perkss/grafana-export
    interpolate:
      path: builtin
      method: Interpolation
      config:
        method: linear
        x:
          - 0
          - 10
          - 50
          - 100
        'y':
          - 0.12
          - 0.32
          - 0.75
          - 1.02
        input-parameter: cpu/utilization
        output-parameter: cpu-factor
    cpu-factor-to-wattage:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - cpu-factor
          - thermal-design-power
        output-parameter: cpu-wattage
    wattage-times-duration:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - cpu-wattage
          - duration
        output-parameter: cpu-wattage-times-duration
    wattage-to-energy-kwh:
      path: builtin
      method: Divide
      config:
        numerator: cpu-wattage-times-duration
        denominator: 3600000
        output: cpu-energy-raw
    calculate-vcpu-ratio:
      path: builtin
      method: Divide
      config:
        numerator: vcpus-total
        denominator: vcpus-allocated
        output: vcpu-ratio
    correct-cpu-energy-for-vcpu-ratio:
      path: builtin
      method: Divide
      config:
        numerator: cpu-energy-raw
        denominator: vcpu-ratio
        output: cpu-energy-kwh
    energy-to-carbon:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - grid-carbon-intensity
          - cpu-energy-kwh
        output-parameter: carbon
tree:
  children:
    child:
      pipeline:
        observe:
          - mock-observations
        regroup:
        compute:
          - interpolate
          - cpu-factor-to-wattage
          - wattage-times-duration
          - wattage-to-energy-kwh
          - calculate-vcpu-ratio
          - correct-cpu-energy-for-vcpu-ratio
          - energy-to-carbon
          - grafana-exporter
      config:
        grafana-exporter:
          output-path: /Users/leonardovicentini/Desktop/Magistrale/Theses/system/if-poc/csv/teads-curve-demo.csv
          headers:
            - timestamp
            - duration
            - carbon
            - cpu/utilization
            - thermal-design-power
            - vcpus-total
            - vcpus-allocated
            - grid-carbon-intensity
            - cpu-factor
            - cpu-wattage
            - cpu-wattage-times-duration
            - cpu-energy-raw
            - vcpu-ratio
            - cpu-energy-kwh
      defaults:
        thermal-design-power: 100
        vcpus-total: 8
        vcpus-allocated: 2
        grid-carbon-intensity: 750
      inputs:
        